name: Start jksb

on:
  workflow_dispatch:
  schedule:
    - cron: '05 16,17,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start zzu_auto_jksb
      env:
          jksb_username: ${{ secrets.jksb_username }}
          jksb_password: ${{ secrets.jksb_password }}
          jksb_code_province: ${{ secrets.jksb_code_province }}
          jksb_code_city: ${{ secrets.jksb_code_city }}
          jksb_location: ${{ secrets.jksb_location }}
          jksb_vaccine: ${{ secrets.jksb_vaccine }}
          jksb_jingdu: ${{ secrets.jksb_jingdu }}
          jksb_weidu: ${{ secrets.jksb_weidu }}
          jksb_send_type: ${{ secrets.jksb_send_type }}
          jksb_send_parameter: ${{ secrets.jksb_send_parameter }}
          jksb_baidu_API_Key: ${{ secrets.jksb_baidu_API_Key }}
          jksb_baidu_Secret_Key: ${{ secrets.jksb_baidu_Secret_Key }}
          jksb_zhb_parameter: ${{ secrets.jksb_zhb_parameter }}
      run: |
        python jksb.py